---
# Role tasks

- block:
    - name: Gather address
      shell: >-
        set -o pipefail ;
        dig -t A {{ etc_hosts_item.1 }} +search
        | grep -v "^;"
        | grep -v "^$"
        | grep " IN A "
        | head -1
        | awk '{print $5}'
      args:
        warn: no
      when: etc_hosts_item.0.address is undefined
      register: etc_hosts_gather_address_result
      changed_when: no
      failed_when: no
      loop: "{{ etc_hosts_items_to_manage | subelements('hostnames') }}"
      loop_control:
        loop_var: etc_hosts_item
        label: "{{ etc_hosts_item.1 }}"

    - name: Setup /etc/hosts entries
      lineinfile:
        dest: /etc/hosts
        regexp: "^{{ etc_hosts_item.address }} "
        line: >-
          {{ etc_hosts_item.address }}
          {{ etc_hosts_item.hostnames | join(' ') }}
        state: "{{ etc_hosts_item.state | default('present') }}"
        backup: yes
      loop: "{{ etc_hosts_items_to_manage_expanded }}"
      loop_control:
        loop_var: etc_hosts_item
        label: "{{ etc_hosts_item.address }}"
  tags:
    - role::etc_hosts
