---
# Role tasks

- include_role:
    name: amtega.check_platform
  vars:
    check_platform_distributions:
      centos: 6
      debian: 9
      fedora: 29
      rhel: 6

- include_role:
    name: amtega.select_hostvars
  vars:
    select_hostvars_query:
      pattern: "^etc_hosts_.*"
      attributes:
        - hostnames
      fact_name: etc_hosts_hostvars
      output_type: list
  when: etc_hosts_load_from_hostvars | bool

- block:
    - name: Setup /etc/hosts entries
      lineinfile:
        dest: /etc/hosts
        regexp: "^{{ etc_hosts_item.address }} "
        line: >-
          {{ etc_hosts_item.address }}
          {{ etc_hosts_item.hostnames | join(' ') }}
        state: "{{ etc_hosts_item.state | default('present') }}"
      loop: "{{ etc_hosts_to_manage }}"
      loop_control:
        loop_var: etc_hosts_item
        label: "{{ etc_hosts_item.address }}"
  vars:
    etc_hosts_to_manage: >-
      {{ lookup("template", "entries.yml.j2") | from_yaml }}
  tags:
    - role::etc_hosts
