---

- name: Prepare
  hosts: molecule_hosts
  gather_facts: no
  become: yes
  # roles:
  #   - amtega.selinux

  # tasks:
  #   - name: Setup packages
  #     package:
  #       name: libselinux-python
  #       state: present
